# Tensor Basics

In [35]:
import torch


#make a random tensor of size (4,3)
x = torch.rand(4, 3)
print(x)

tensor([[0.4962, 0.3283, 0.2880],
        [0.9919, 0.0760, 0.4430],
        [0.8144, 0.2757, 0.0582],
        [0.0638, 0.8576, 0.2968]])


In [36]:
#intialize a tensor of size (2,3) with zeros
x = torch.zeros(2, 3, dtype=torch.int)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [38]:
#You can even make a tensor from your given list of numbers
x = torch.tensor([4, 3])
print(x)

tensor([4, 3])


In [39]:
#You can transfer the property of one tensor x to the another new tensor y.

x = torch.rand(2, 3)
print(x)

y = torch.randn_like(x, dtype=torch.float)    
print(y)

tensor([[0.5913, 0.9356, 0.1400],
        [0.2191, 0.8193, 0.4834]])
tensor([[-0.3078, -0.1623, -0.4389],
        [ 0.3400, -0.1067, -0.4914]])


In [40]:
#to check the size of tensor

print(x.size())
print(y.size())

torch.Size([2, 3])
torch.Size([2, 3])


# Tensor Mathematical Operations

1. Tensor Addition

In [43]:
#Method 1:

x = torch.rand(4, 3)
y = torch.rand(4, 3)

print(x + y)

tensor([[1.2799, 1.6521, 0.5554],
        [1.7620, 1.5549, 0.8005],
        [1.2057, 1.3362, 0.8216],
        [1.5876, 1.8165, 1.1236]])


In [44]:
#Method 2:

print(torch.add(x, y))

tensor([[1.2799, 1.6521, 0.5554],
        [1.7620, 1.5549, 0.8005],
        [1.2057, 1.3362, 0.8216],
        [1.5876, 1.8165, 1.1236]])


2. Tensor Subtraction

In [45]:
#Method 1:

x = torch.rand(4, 3)
y = torch.rand(4, 3)

print(x - y)

tensor([[ 0.6589,  0.0509, -0.7930],
        [-0.2612,  0.0733,  0.6093],
        [-0.3240,  0.1778, -0.6672],
        [-0.8397, -0.8389,  0.3115]])


In [46]:
#Method 2:

print(torch.sub(x, y))

tensor([[ 0.6589,  0.0509, -0.7930],
        [-0.2612,  0.0733,  0.6093],
        [-0.3240,  0.1778, -0.6672],
        [-0.8397, -0.8389,  0.3115]])


3. Tensor Product or Mutliplication

In [47]:
# If m1 is a (n×m) tensor, m2 is a (m×p) tensor, output will be a (n×p) tensor

m1 = torch.randn(2, 3)
m2 = torch.randn(3, 3)

print(torch.mm(m1, m2))

tensor([[-1.6092, -4.3108, -2.2888],
        [-1.5063, -2.2422, -1.2025]])


# Tensor Indexing and Slicing

1. Indexing

In [49]:
#Accessing the tensor data

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][0])

tensor(4)


2. Slicing

In [51]:
x[0][2] = 7
print(x)

tensor([[1, 2, 7],
        [4, 5, 6]])
